### ISSUE TITLE
Google Cloud plugins

### ISSUE THREAD

**Issue by Vadorequest** [serverless/plugins#131]
I'm getting started with serverless and feels like all plugins are for AWS. Is it because GCF support is somehow new?

**Comment by Vadorequest** [comment]
https://forum.serverless.com/t/getting-started-with-gcp-a-hassle/3755/4

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss plugin ideas at https://github.com/serverless/serverless/discussions
