### ISSUE TITLE
serverless-localstack plugin

### ISSUE THREAD

**Issue by chenrui333** [serverless/plugins#162]
This seems a nice plugin which local test against `localstack`?
https://github.com/temyers/serverless-localstack

**Comment by eahefnawy** [comment]
@chenrui333 yep agreed. Did you have a chance to test it?

**Comment by chenrui333** [comment]
@eahefnawy Sure, I can do some testing and get some feedback in here.

**Comment by eahefnawy** [comment]
awesome! Thanks @chenrui333 ... if it works as expected, we'd really appreciate a PR that adds this awesome plugin to our official list of plugins 💪

**Comment by exoego** [comment]
😢Unfortunately serverless-localstack is archived.
Hope someone create a fork and continue development.

**Comment by nosahama** [comment]
> 😢Unfortunately serverless-localstack is archived.
> Hope someone create a fork and continue development.

Owner was transferred, see - https://github.com/localstack/serverless-localstack

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss plugin ideas at https://github.com/serverless/serverless/discussions
