### ISSUE TITLE
a plugin to print sls configuration a-la yq

### ISSUE THREAD

**Issue by ronkorving** [serverless/plugins#164]
It could be pretty useful if `sls` were able to print out its configuration, or parts of it, in plain text, via some command line argument.

I imagine something like this (for my use-case):

```sh
export FUNCTIONS="${sls print-config 'keys(functions)'}"
for FUNCTION in ${FUNCTIONS}
do
  sls deploy function -f ${FUNCTION}
done
```

**Comment by dschep** [comment]
closed by serverless/serverless#5036
