### ISSUE TITLE
serverless-plugin-cloudwatch-dashboard

### ISSUE THREAD

**Issue by cw43** [serverless/plugins#215]
Hi there,

I've developed a new Serverless plugin for generating CloudWatch dashboards for lambda functions:
[https://github.com/codecentric/serverless-plugin-cloudwatch-dashboard](https://github.com/codecentric/serverless-plugin-cloudwatch-dashboard)

Would it be of any interest to the community here? I'd be glad to have the experts opinion on it.

Thanks :)

**Comment by eahefnawy** [comment]
this looks really cool @cw43! why don't you PR it to include it in the community list of plugins? 😊 

https://github.com/serverless/plugins#community-contributed-plugins

**Comment by cw43** [comment]
I just created the PR. Thanks @eahefnawy for your feedback :)
