### ISSUE TITLE
Serverless plugin for AWS Lex

### ISSUE THREAD

**Issue by pavelsavara** [serverless/plugins#233]
Hi guys,

in last two days I implemented crude serverless plugin for deployment of AWS Lex. 
https://github.com/pavelsavara/serverless-plugin-lex-bot
I would like to donate the code to community under MIT license.

The current implementation is able to convert and deploy NLP model from [Alexa](https://github.com/marcy-terui/serverless-alexa-skills)'s  
yaml in `custom\alexa\skills\models\locale\interactionModel\languageModel` see [serverless.yml](https://github.com/pavelsavara/serverless-plugin-lex-bot/blob/master/test/serverless.yml) sample.
It would convert the Alexa syntax into Lex syntax, create import zip file and upload the bot. (there is no CloudFormation for Lex)
It would also build the bot and label it with `latest` version alias.
Since Lex intents and slot types are global, this plugin will prefix their names with name of the bot and locale.
It would also skip Alexa built-in intent types such as `AMAZON.MoreIntent` which are not supported by Lex. 
Built-in intent types which are supported like `AMAZON.RepeatIntent` would be maped to Lex built-in.

At the moment it's very crude plugin with lot of possible improvements. 
Specifically I think I didn't do good job on plugin command and life-cycle integration, nor logging.
On Lex side of things, I'm newbie too. 

Advice or PR on all aspects of this is welcome!

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss plugin ideas at https://github.com/serverless/serverless/discussions
