### ISSUE TITLE
MFA Plugin created

### ISSUE THREAD

**Issue by alikian** [serverless/plugins#249]
I developed a new plugin which will handle MFA for Serverless. 

- It uses MFA key to generate token
- Using token call STS getSession and retrieve temporary credentials, then 
- Inject this temp credentials to AWS CLI environment variables.

This can be used in any deployment with manual entering MFA token.

Any suggestion to improve welcomes.
https://github.com/alikian/mfa-serverless-plugin

Thanks,
Ali

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss plugin ideas at https://github.com/serverless/serverless/discussions
