### ISSUE TITLE
An organisation for community plugins?

### ISSUE THREAD

**Issue by thenikso** [serverless/plugins#26]
Hello everyone!

I'm the original creator of https://github.com/elastic-coders/serverless-webpack and recently I've been contacted by @domaslasauskas that volunteer to help me maintain the plugin.

That's great given that I only have limited time to maintain it myself.

As he suggested I'd like to move the plugin to a dedicated GitHub organisation which could just be `serverless-webpack`; however I am here to ask if it would make sense to have a `serverless-plugins` organisation or similar.

**Comment by pmuens** [comment]
Neat idea @thenikso 👍 

So the plugins code should live in this org and everyone can maintain all the plugins? Sounds like a good idea 👍 

What do you think @nikgraf @eahefnawy @DavidWells @mthenw ?

Here are some related discussions:
- https://github.com/serverless/serverless/issues/1584
- https://github.com/serverless/serverless/pull/1525

**Comment by domaslasauskas** [comment]
I vote for `serverless-plugins` org that could be home for other community maintained plugins.

**Comment by StevenACoffman** [comment]
Please see elastic-coders/serverless-webpack#133 for related discussion.

**Comment by medikoo** [comment]
If needed we're open to host plugins at [serverless organization](https://github.com/serverless/)
