### ISSUE TITLE
Serverless Alexa

### ISSUE THREAD

**Issue by rajington** [serverless/plugins#3]
Hello,

I have a pretty minor plugin I wrote for my personal project using Alexa, but maybe it's simple enough to start filling out this repo a little.

https://github.com/rajington/serverless-alexa-plugin

Alexa can invoke your Lambda in two ways:

The first is via the Skills Kit, which is by far the most common method, and accomplished via a simple CF permission template.

The second is via Smart Home, which can currently only be configured via the GUI/SDK/CLI. I've stubbed out what a Smart Home CF template might look like, but it doesn't actually work. I might implement the SDKroute if there's enough demand, but it's a lot messier and will probably be short-lived.

**Comment by nikgraf** [comment]
Nice!
