### ISSUE TITLE
missing depencies of serverless@>=1.48.1

### ISSUE THREAD

**Issue by jss49** [serverless/plugins#301]
Setup:
Nodejs 12
serverless-offline 1.58 

Serverless itself is installed and working -> listening to localhost:3000
Trying to install serverless-offline plugin at my project but I always get the following warning:

npm WARN serverless-offline@6.0.0-alpha.46 requires a peer of serverless@>=1.48.1 but none is installed. You must install peer dependencies yourself.

Is a workaround out there? Anybody can help?

Thank you

**Comment by medikoo** [comment]
This is a plugin registry repository. Any issues with the Framework should be reported to its bug tracker: https://github.com/serverless/serverless/issues/new?assignees=&labels=&template=bug-report.yml
