### ISSUE TITLE
Proposing Serverless function announcer plugin

### ISSUE THREAD

**Issue by dee-me-tree-or-love** [serverless/plugins#310]
Hello everone, 

A while ago I wrote a small plugin to announce new function deployments to an arbitrary webhook (used it as a part of service self-registration pattern for SLS functions). To be honest, I don't know if it's still relevant to the community but thought to publish it into the list. 

Would like to ask if you might give a look and tell if it's worthwhile. I wrote it quite a while back, so if you think there should be some code-wise improvements or else, please do let me know, I would much appreciate it. 

The plugin repo is here: https://github.com/dee-me-tree-or-love/serverless-lambda-announcer 
Currently the plugin works only for AWS Lambdas.
If that's a green light, I'll make a pull request.

Cheers everyone, 
 
Dmitrii

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss this kind of things at https://github.com/serverless/serverless/discussions
