### ISSUE TITLE
A Auto-generate functions, Typescript, Decorator, DI Pattern wrapper for serverless

### ISSUE THREAD

**Issue by linrium** [serverless/plugins#322]
When I working with serverless framework, I must write some code again and again so I wrote a wrapper library for serverless. After 3 months of testing and running on production at AhaMove. I want to share with the community about this library. Here is my [Medium](https://medium.com/@linrium/ahaless-write-serverless-application-oop-on-top-of-typescript-ffbab8e5c4db) blog.

Summary the library features:
- Auto-generate functions name - you don't need to update or write it yourself anymore ([serverless-generate-functions])(https://github.com/lynkxyz/serverless-generate-functions))
- Support typescript with hot reload ([serverless-plugin-typescript](https://github.com/prisma-labs/serverless-plugin-typescript))
- Offline ([serverless-offline](https://github.com/dherault/serverless-offline))
- Environment files ([serverless-dotenv-plugin](https://github.com/colynb/serverless-dotenv-plugin))
- Support DI pattern, decorator ([ahaless](https://github.com/lynkxyz/ahaless))

TODO:
- Asynchronous providers
- Circular dependency
- Testing

If everybody likes this project, it open to contribute or feedback to me then I will update it later :D

**Comment by medikoo** [comment]
This is a plugin registry repository. Let's discuss serverless related development challenges at https://github.com/serverless/serverless/discussions
