### ISSUE TITLE
Better TypeScript plugin

### ISSUE THREAD

**Issue by tpscrpt** [serverless/plugins#325]
The current standard for using TypeScript with serverless is https://github.com/prisma-labs/serverless-plugin-typescript

Unfortunately, this package has not been updated in almost 1 year, so people actually using it probably won't be too comfortable deploying production projects with it.

Another fork exists, which patches a few of the issues present in the plugin (https://github.com/KingDarBoja/serverless-plugin-typescript), but that maintainer also mentioned that they don't have a lot of time to work on it.

I would like to propose the plugin be replaced with my version of it, which has some more features for DX and perf considerations. I've also made a very detailed template which uses to demonstrate how one could organize a TypeScript/Serverless repo in a way that makes sense.

My fork of the plugin: https://github.com/jeremigendron/sls-ts-plugin
My template using this plugin: https://github.com/jeremigendron/sls-ts-template

Thread outlining lack of activity in the original (dead) plugin: https://github.com/prisma-labs/serverless-plugin-typescript/issues/201

Discussion between me and the second maintainer (the one who forked the dead plugin): https://github.com/KingDarBoja/serverless-plugin-typescript/pull/8

LMK if this is wanted

**Comment by medikoo** [comment]
`serverless-plugin-typescript` is now maintained by Serverless Framework team and is ensured to work properly with latest version of a Framework. Please upgrade.

Also this is a plugin registry repository, it's better to discuss this kind of matters at  https://github.com/serverless/serverless/discussions
