### ISSUE TITLE
An idea for a new plugin: A "webpack-like" plugin to compress Python source code to tackle FaaS cold start

### ISSUE THREAD

**Issue by andre-marcos-perez** [serverless/plugins#331]
**Cold start** is well known ~~problem~~ feature of any FaaS. 

@mikhailshilkov wrote a nice **[article ](https://mikhail.io/serverless/coldstarts/aws/)** on the topic where he points out the impact of serverless function features on the cold start time. In special he shows how the **package size** slows down the startup time on cold start situations.

Javascript web apps extensively use **[webpack](https://github.com/webpack)** to compress source code, thus speeding up web content delivery. The serverless community have been already leveraging this idea through plugins for javascript based serverless functions, e.g.: **[serverless-webpack](https://github.com/serverless-heaven/serverless-webpack)**.

How about a *webpack-like-plugin* for python based serveless functions?

There are some packages out there. The **[pyminifier](https://github.com/liftoff/pyminifier)** have reached as high as ~50% of compression rate, according to its documentation. A plugin to compress python code could potentially improve the perfomance of python based serverless functions against cold start situations.

What do you guys think?

**Comment by chrisVillanueva** [comment]
I like this approach.  Thanks for sharing info about pyminifier.

**Comment by weitang2021** [comment]
Any update on this? lambda@edge on aws has a size limit of 1MB. This would greatly help it.

**Comment by medikoo** [comment]
This is a plugin registry repository. Let's discuss serverless related development challenges at https://github.com/serverless/serverless/discussions
