### ISSUE TITLE
serverless.yml package should allow to define codeUri

### ISSUE THREAD

**Issue by tamsler** [serverless/plugins#335]
The serverless.yml package section should allow to define a codeUri which will be use as the base path for generating the zip archive.

e.g. Code
src/handler/index.js
src/lib/service.js

serverless.yml
package:
   codeUri: ./src

will would generate a zip archive containing:
handler/index.js
lib/service.js

This would be a similar capability that AWS SAM offers via: CodeUri: ./src
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html

**Comment by medikoo** [comment]
This is a plugin registry repository, to request a Serveless Framework feature please report at its repository: https://github.com/serverless/serverless/issues/new/choose
