### ISSUE TITLE
Interoperate with Terraform DynamoDB locks

### ISSUE THREAD

**Issue by nl-brett-stime** [serverless/plugins#356]
Moving from https://github.com/serverless/serverless/issues/8663#issuecomment-750103511 .

Use case description

When using the Terraform S3 'backend', it's possible to configure a DynamoDB table for locking:

https://www.terraform.io/docs/state/locking.html
https://www.terraform.io/docs/backends/types/s3.html#dynamodb_table

This TF feature attempts to perform a conditional write to a DynamoDB table before making changes to the resources protected by the lock. If some other user has already begun modifying the protected resources through Terraform, the write condition will fail and the second user will have to wait until the first user has finished making their modifications. This prevents two users from trying to modify the controlled resources at the same time.

Some Serverless features such as Cognito User Pool trigger events modify existing resources. It'd be a good safety feature to tell Serverless to take a list of arbitrary locks that are compatible with Terraform to ensure that resources that are partially managed by both SLS and TF aren't being modified at the same time.
Proposed solution

Add a section in serverless.yml like the following:

terraformDynamoDbLocks:
  - someLockName:
      table: someTableName
      bucket: someBucketName
      workspace_key_prefix: someKeyPrefix
      workspace: someWorkspace
      key: someKey

When running e.g., serverless deploy if Serverless is unable to acquire any of the declared locks it should throw an error message like, "Unable to acquire lock for 'someBucketName/someKeyPrefix/someWorkspace/someKey' the lock was acquired by other.user@your.org at 2020-12-22T15:22:43.960627Z. If you're sure they're done managing the remote state, you can force an unlock by running the following command: serverless terraform-force-unlock someLockName 1a756b9b-93b2-91c3-3811-098b884033aa". It's already possible to use Terraform itself to force the unlock so that part of the feature would be less urgent but convenient for users who didn't also already have easy access to a configured Terraform installation.

Serverless should revert any locks it's created once it's done attempting it's modifications.

**Comment by medikoo** [comment]
This is a plugin registry, to discuss issues related to how to set up Serverless projects please use https://github.com/serverless/serverless/discussions
