### ISSUE TITLE
Serverless Plugin Webpack

### ISSUE THREAD

**Issue by jogold** [serverless/plugins#36]
Hello,

I made another webpack plugin with the following features/advantages:
- Zero configuration
- Functions are packaged individually, resulting in Lambda deployment packages (zip) containing only the code needed to run the function (no bloat)
- Uses an *array* of webpack configurations instead of one webpack configuration with multiple entry points, resulting in better tree-shaking because dependencies are isolated (see [Tree shaking](https://github.com/FormidableLabs/formidable-playbook/blob/master/docs/frontend/webpack-tree-shaking.md)).

See **https://github.com/goldwasserexchange/serverless-plugin-webpack**

**Comment by jogold** [comment]
See #37.

Thank you !

**Comment by pmuens** [comment]
Thanks @jogold 👍
