### ISSUE TITLE
Serverless Offline Plugin No Longer Being Actively Maintained

### ISSUE THREAD

**Issue by selected-pixel-jameson** [serverless/plugins#364]
Hello,

I know this is probably not where this should be posted, but I'm not sure where else to alert the Serverless Team about this. 
It seems as if the `serverless-offline` plugin's repository owner has gone dark. I haven't seen him respond to any questions or comments since October. Hoping everything is ok.

That being said, this plugin seems like a pretty integral part of the Serverless framework and I was wondering if the Serverless team would consider bringing it in as a supported plugin?

Currently the plugin has not seen an update in approximately 6 months. This is a huge part of my development process and I'm sure thousands of others. Without this plugin I wouldn't be able to use the Serverless Framework in a practical sense.

I've posted a similar question on the `serverless-offline` repo. There seems to be slight traction towards getting the minimum  updates (NodeJS 14) support implemented, but beyond that it seems pretty stagnant. 

Thank you!

**Comment by pgrzesik** [comment]
Hello @selected-pixel-jameson, thanks for reaching out. We're aware of the situation and we've contacted the maintainer and are currently in the process of transferring ownership so we will be able to help out with maintenance and development of the plugin. :+1:
