### ISSUE TITLE
serverless-plugin-optimize

### ISSUE THREAD

**Issue by goncaloneves** [serverless/plugins#6]
I was looking for a plugin that would automate bundling, transpiling to ES5 and minification like serverless-optimizer-plugin was doing in v0.5.x to make package exclusion handling a lot easier.

So I have a built a child plugin that does the same and allows to exclude modules globally and by function.

https://github.com/FidelLimited/serverless-plugin-optimize

Have a look and let me know how it works in your SLS setup. 👌

**Comment by DavidWells** [comment]
Awesome! It's on the list =) 

Closing this
