### ISSUE TITLE
AWS Step Functions offline

### ISSUE THREAD

**Issue by vicneanschi** [serverless/plugins#96]
Is there a plugin to support [Step Functions](https://aws.amazon.com/step-functions/) in offline mode?

This would require an implementation of [State Machine](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-states.html)  which is described by [Amazon States Language](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html).

For starters it would be enough to support just one [type of tasks](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-tasks.html) - [Lambda Function](http://docs.aws.amazon.com/step-functions/latest/dg/tutorial-creating-lambda-state-machine.html).

**Comment by vkkis93** [comment]
Hello Guys 
I wrote plugin which can help you run step function offline/locally.

https://github.com/vkkis93/serverless-step-functions-offline

At this moment plugin in beta version, but it support a few states like Wait, Choice, Parallel, Task. Some of states has limitation support.
Plugin support only runtime node.js and works only with callback. 
Currently does not work with context object.

**Comment by tristanbenier** [comment]
Hi guys,

We developed a node package to run a local Step Functions server.

https://www.npmjs.com/package/stepfunctions-local/

It is fully compliant with AWS Step Functions API. You can easily query it by changing the endpoint.  
You can either start a local server from your JS code or directly with the CLI.

The project is currently in alpha version and every contribution is warm welcome on our [Github](https://github.com/airware/stepfunctions-local).

**Comment by pianomansam** [comment]
As I mentioned on [serverless-step-functions#105](https://github.com/horike37/serverless-step-functions/issues/105), I just started on a plugin that supports step functions in serverless offline.

https://github.com/pianomansam/serverless-offline-stepfunctions

I also created a plugin to automatically start/stop the wonderful stepfunctions-local by @tristanbenier and @ChristopheBougere so we have a local Step Functions server:

https://github.com/pianomansam/serverless-offline-stepfunctions-local

**Comment by medikoo** [comment]
This is a plugin registry repository, where exchange should rather be limited to the state of this registry, and not to discuss ideas for plugins.

I propose to discuss plugin ideas at https://github.com/serverless/serverless/discussions
